const links = [
  { name: 'YouTube', url: 'https://www.youtube.com' },
  { name: 'Pinterest', url: 'https://www.pinterest.com' },
  { name: 'SoundCloud', url: 'https://soundcloud.com' },
  { name: 'OpenClassrooms', url: 'https://openclassrooms.com/fr/dashboard/courses' },
  { name: 'Facebook', url: 'https://www.facebook.com' },
  { name: 'Duolingo', url: 'https://www.duolingo.com' },
  { name: 'Twitter', url: 'https://www.twitter.com' },
  { name: 'Instagram', url: 'https://www.instagram.com' },
  { name: 'GitHub', url: 'https://www.github.com' },
  { name: 'Stack Overflow', url: 'https://stackoverflow.com' },
  { name: 'Reddit', url: 'https://www.reddit.com' },
  { name: 'Wikipedia', url: 'https://www.wikipedia.org' },
  { name: 'Amazon', url: 'https://www.amazon.com' },
  { name: 'LinkedIn', url: 'https://www.linkedin.com' },
  { name: 'Netflix', url: 'https://www.netflix.com' },
  { name: 'Spotify', url: 'https://www.spotify.com' },
  { name: 'Google', url: 'https://www.google.com' },
  { name: 'Twitch', url: 'https://www.twitch.tv' },
  { name: 'YouTube Music', url: 'https://music.youtube.com' },
  { name: 'Vimeo', url: 'https://www.vimeo.com' },
  { name: 'Dropbox', url: 'https://www.dropbox.com' },
  { name: 'Trello', url: 'https://www.trello.com' },
  { name: 'Slack', url: 'https://www.slack.com' },
  { name: 'Quora', url: 'https://www.quora.com' },
  { name: 'Medium', url: 'https://www.medium.com' },
  { name: 'Wikipedia en français', url: 'https://fr.wikipedia.org' },
  { name: 'Etsy', url: 'https://www.etsy.com' },
  { name: 'Airbnb', url: 'https://www.airbnb.com' },
  { name: 'Coursera', url: 'https://www.coursera.org' },
  { name: 'Udemy', url: 'https://www.udemy.com' },
  { name: 'GitLab', url: 'https://www.gitlab.com' },
  { name: 'Bing', url: 'https://www.bing.com' },
  { name: 'IMDB', url: 'https://www.imdb.com' },
  { name: 'Flickr', url: 'https://www.flickr.com' },
  { name: 'Zoom', url: 'https://www.zoom.us' }
];


export default links